# .goreleaser.yaml
version: 2

before:
  hooks:
    - bash -c "cd backend && go mod tidy"
    # The frontend is built by the GHA workflow before running goreleaser

builds:
  - id: ss-ui
    dir: backend
    main: ./cmd/server
    binary: ss-ui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - image_templates:
      - "quay.io/acaglio/ss-ui:{{ .Version }}"
      - "quay.io/acaglio/ss-ui:latest"
    dockerfile: backend/Containerfile.release
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "merge"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*!?:.+$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*!?:.+$"
      order: 1
    - title: Others
      regexp: "^.*:.+$"
      order: 999

release:
  github:
    owner: alessandrocaglio
    name: ss-ui
